#:schema node_modules/wrangler/config-schema.json
name = "xrainget"
main = "src/index.js"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]
workers_dev = true
[observability]
enabled = true
head_sampling_rate = 1
[placement]
mode = "smart"
